sudo: reruired
services:
  - docker

before_install:
  - docker build -t yasardeen/react-dev-testapp -f ./client/Dockerfile.dev ./client

script:
  - docker run yasardeen/react-dev-testapp npm test -- --coverage

after_success:
  - docker build -t 469996/multi-client ./client
  - docker build -t 469996/multi-nginx ./nginx
  - docker build -t 469996/multi-server ./server
  - docker build -t 469996/multi-worker ./worker
  #log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push the images to docker hub
  - docker push 469996/multi-client
  - docker push 469996/multi-nginx
  - docker push 469996/multi-server
  - docker push 469996/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app:  multi-docker-deployment
  env: MultiDockerDeployment-env
  bucket_name: elasticbeanstalk-us-east-1-766940135267
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



